### ISSUE TITLE
您好！请教IOS端的集成

### ISSUE THREAD

**Issue by shijia2118** [lowapple/flutter-pixelmatching#5]
您好！我正在集成flutter+ffi+opencv的插件，借鉴了您的这个插件项目。android端已经顺利完成，但是在IOS端在接入opencv后，运行项目时会报各种错误。不知道您的IOS端是怎么集成的，可以沟通下吗？十分感谢！

**Comment by lowapple** [comment]
@shijia2118 
Hi, sorry for the late reply.
I was wondering if you could tell me your Flutter version?
And I was wondering what errors you are getting.
